import styled, { createGlobalStyle, css, keyframes, ThemeProvider } from "styled-components";
import { themeGet } from "@styled-system/theme-get";
import tinycolor from "tinycolor2";
import { classicTheme, darkTheme, fairplayTheme } from "./theme";
export declare const device: {
    small: string;
    medium: string;
    large: string;
    xlarge: string;
    xxlarge: string;
    mdToLg: string;
    lgToXl: string;
};
declare const themes: {
    classic: {
        fontSize: {
            body: string;
            h1: string[];
            h2: string[];
            h3: string[];
            h4: string[];
            h5: string[];
            h6: string[];
        };
        fonts: {
            body: string;
            heading: string;
            googleSansRegular: string;
            googleSansMedium: string;
            googleSansBold: string;
        };
        fontWeights: {
            body: number;
            heading: number;
        };
        lineHeights: {
            body: number;
            heading: number;
        };
        radii: {
            sm: string;
            md: string;
            lg: string;
            rounded: string;
            circle: string;
            pill: string;
        };
        shadows: {
            default: string;
            sm: string;
            lg: string;
            input: string;
        };
        breakpoints: string[];
        transition: string;
        anchor: {
            primary: {
                color: string;
                bg: string;
            };
        };
        name: string;
        colors: {
            primary: string;
            secondary: string;
            success: string;
            info: string;
            warning: string;
            danger: string;
            light: string;
            dark: string;
            text: string;
            text2: string;
            text3: string;
            text4: string;
            heading: string;
            link: string;
            background: string;
            hover: string;
            headerbtnbg: string;
            white: string;
            black: string;
            close: string;
            border: string;
            gray50: string;
            gray100: string;
            gray200: string;
            gray300: string;
            gray400: string;
            gray500: string;
            gray600: string;
            gray700: string;
            gray800: string;
            gray900: string;
            gray950: string;
            whisper: string;
            malibu: string;
            tropical: string;
            pink: string;
            bayoux: string;
            athens: string;
            athens2: string;
            athens3: string;
            orange: string;
            cyan: string;
            teal: string;
            indigo: string;
            vulcan: string;
            litecoin: string;
            lightblue: string;
            brand2: string;
            shuttle: string;
            science: string;
            facebook: string;
            twitter: string;
            shuttle2: string;
            lilac: string;
            catskill: string;
            gulf: string;
            river: string;
            zircon: string;
            clay: string;
            clay2: string;
            shaft: string;
            cod: string;
            silver: string;
        };
    };
    light: {
        fontSize: {
            body: string;
            h1: string[];
            h2: string[];
            h3: string[];
            h4: string[];
            h5: string[];
            h6: string[];
        };
        fonts: {
            body: string;
            heading: string;
            googleSansRegular: string;
            googleSansMedium: string;
            googleSansBold: string;
        };
        fontWeights: {
            body: number;
            heading: number;
        };
        lineHeights: {
            body: number;
            heading: number;
        };
        radii: {
            sm: string;
            md: string;
            lg: string;
            rounded: string;
            circle: string;
            pill: string;
        };
        shadows: {
            default: string;
            sm: string;
            lg: string;
            input: string;
        };
        breakpoints: string[];
        transition: string;
        anchor: {
            primary: {
                color: string;
                bg: string;
            };
        };
        name: string;
        colors: {
            primary: string;
            secondary: string;
            success: string;
            info: string;
            warning: string;
            danger: string;
            light: string;
            dark: string;
            text: string;
            text2: string;
            text3: string;
            text4: string;
            heading: string;
            link: string;
            background: string;
            hover: string;
            white: string;
            black: string;
            close: string;
            border: string;
            gray50: string;
            gray100: string;
            gray200: string;
            gray300: string;
            gray400: string;
            gray500: string;
            gray600: string;
            gray700: string;
            gray800: string;
            gray900: string;
            gray950: string;
            whisper: string;
            malibu: string;
            tropical: string;
            pink: string;
            bayoux: string;
            athens: string;
            athens2: string;
            athens3: string;
            orange: string;
            cyan: string;
            teal: string;
            indigo: string;
            vulcan: string;
            litecoin: string;
            lightblue: string;
            brand2: string;
            shuttle: string;
            science: string;
            facebook: string;
            twitter: string;
            shuttle2: string;
            lilac: string;
            catskill: string;
            gulf: string;
            cornflower: string;
            river: string;
            zircon: string;
            clay: string;
            clay2: string;
            shaft: string;
            cod: string;
            silver: string;
        };
    };
    cool: {
        fontSize: {
            body: string;
            h1: string[];
            h2: string[];
            h3: string[];
            h4: string[];
            h5: string[];
            h6: string[];
        };
        fonts: {
            body: string;
            heading: string;
            googleSansRegular: string;
            googleSansMedium: string;
            googleSansBold: string;
        };
        fontWeights: {
            body: number;
            heading: number;
        };
        lineHeights: {
            body: number;
            heading: number;
        };
        radii: {
            sm: string;
            md: string;
            lg: string;
            rounded: string;
            circle: string;
            pill: string;
        };
        shadows: {
            default: string;
            sm: string;
            lg: string;
            input: string;
        };
        breakpoints: string[];
        transition: string;
        anchor: {
            primary: {
                color: string;
                bg: string;
            };
        };
        name: string;
        colors: {
            primary: string;
            secondary: string;
            success: string;
            info: string;
            warning: string;
            danger: string;
            light: string;
            dark: string;
            text: string;
            text2: string;
            text3: string;
            text4: string;
            heading: string;
            link: string;
            background: string;
            hover: string;
            white: string;
            black: string;
            close: string;
            border: string;
            gray50: string;
            gray100: string;
            gray200: string;
            gray300: string;
            gray400: string;
            gray500: string;
            gray600: string;
            gray700: string;
            gray800: string;
            gray900: string;
            gray950: string;
            whisper: string;
            malibu: string;
            tropical: string;
            pink: string;
            bayoux: string;
            athens: string;
            athens2: string;
            athens3: string;
            orange: string;
            cyan: string;
            teal: string;
            indigo: string;
            vulcan: string;
            litecoin: string;
            lightblue: string;
            brand2: string;
            shuttle: string;
            science: string;
            facebook: string;
            twitter: string;
            shuttle2: string;
            lilac: string;
            catskill: string;
            gulf: string;
            cornflower: string;
            river: string;
            zircon: string;
            clay: string;
            clay2: string;
            shaft: string;
            cod: string;
            silver: string;
            skinUi01: string;
        };
    };
    dark: {
        fontSize: {
            body: string;
            h1: string[];
            h2: string[];
            h3: string[];
            h4: string[];
            h5: string[];
            h6: string[];
        };
        fonts: {
            body: string;
            heading: string;
            googleSansRegular: string;
            googleSansMedium: string;
            googleSansBold: string;
        };
        fontWeights: {
            body: number;
            heading: number;
        };
        lineHeights: {
            body: number;
            heading: number;
        };
        radii: {
            sm: string;
            md: string;
            lg: string;
            rounded: string;
            circle: string;
            pill: string;
        };
        shadows: {
            default: string;
            sm: string;
            lg: string;
            input: string;
        };
        breakpoints: string[];
        transition: string;
        anchor: {
            primary: {
                color: string;
                bg: string;
            };
        };
        name: string;
        colors: {
            primary: string;
            secondary: string;
            success: string;
            info: string;
            warning: string;
            danger: string;
            light: string;
            dark: string;
            text: string;
            text2: string;
            text3: string;
            text4: string;
            heading: string;
            link: string;
            background: string;
            hover: string;
            white: string;
            black: string;
            close: string;
            border: string;
            heather: string;
            headerbtnbg: string;
            gray50: string;
            gray100: string;
            gray200: string;
            gray300: string;
            gray400: string;
            gray500: string;
            gray600: string;
            gray700: string;
            gray800: string;
            gray900: string;
            gray950: string;
            whisper: string;
            malibu: string;
            tropical: string;
            pink: string;
            bayoux: string;
            athens: string;
            athens2: string;
            athens3: string;
            orange: string;
            cyan: string;
            teal: string;
            indigo: string;
            vulcan: string;
            litecoin: string;
            lightblue: string;
            brand2: string;
            shuttle: string;
            science: string;
            facebook: string;
            twitter: string;
            shuttle2: string;
            lilac: string;
            catskill: string;
            gulf: string;
            cornflower: string;
            river: string;
            zircon: string;
            clay: string;
            clay2: string;
            shaft: string;
            cod: string;
            silver: string;
            darklighten5: string;
            darklighten2: string;
            darklighten8: string;
            darklighten3: string;
            darkdarken2: string;
            darkdarken3: string;
            darkdarken5: string;
        };
    };
    fairplay: {
        fontSize: {
            body: string;
            h1: string[];
            h2: string[];
            h3: string[];
            h4: string[];
            h5: string[];
            h6: string[];
        };
        fonts: {
            body: string;
            heading: string;
            googleSansRegular: string;
            googleSansMedium: string;
            googleSansBold: string;
        };
        fontWeights: {
            body: number;
            heading: number;
        };
        lineHeights: {
            body: number;
            heading: number;
        };
        radii: {
            sm: string;
            md: string;
            lg: string;
            rounded: string;
            circle: string;
            pill: string;
        };
        shadows: {
            default: string;
            sm: string;
            lg: string;
            input: string;
        };
        breakpoints: string[];
        transition: string;
        anchor: {
            primary: {
                color: string;
                bg: string;
            };
        };
        name: string;
        colors: {
            primary: string;
            secondary: string;
            success: string;
            info: string;
            warning: string;
            danger: string;
            light: string;
            dark: string;
            text: string;
            text2: string;
            text3: string;
            text4: string;
            heading: string;
            link: string;
            background: string;
            hover: string;
            white: string;
            black: string;
            close: string;
            border: string;
            heather: string;
            headerbtnbg: string;
            gray50: string;
            gray100: string;
            gray200: string;
            gray300: string;
            gray400: string;
            gray500: string;
            gray600: string;
            gray700: string;
            gray800: string;
            gray900: string;
            gray950: string;
            whisper: string;
            malibu: string;
            tropical: string;
            pink: string;
            bayoux: string;
            athens: string;
            athens2: string;
            athens3: string;
            orange: string;
            cyan: string;
            teal: string;
            indigo: string;
            vulcan: string;
            litecoin: string;
            lightblue: string;
            brand2: string;
            shuttle: string;
            science: string;
            facebook: string;
            twitter: string;
            shuttle2: string;
            lilac: string;
            catskill: string;
            gulf: string;
            cornflower: string;
            river: string;
            zircon: string;
            clay: string;
            clay2: string;
            shaft: string;
            cod: string;
            silver: string;
            darklighten5: string;
            darklighten2: string;
            darklighten8: string;
            darklighten3: string;
            darkdarken2: string;
            darkdarken3: string;
            darkdarken5: string;
        };
    };
};
export { createGlobalStyle, css, keyframes, ThemeProvider, themeGet, classicTheme, darkTheme, fairplayTheme, tinycolor, themes, };
export * from "styled-system";
export default styled;
